name: wordify-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        pip install tox tox-gh-actions
    - name: Run tox
      run: tox
    - name: Flake8
      uses: cclauss/GitHub-Action-for-Flake8@v0.5.0
      with:
        args: flake8 wordifier tests --count --show-source --statistics
